[default]

    [default.nmap-top-1000-tcp]

        [default.nmap-top-1000-tcp.service-detection]
        command = 'nmap {nmap_extra} -sS -sV -n -Pn -vv --top-ports 1000 --open -T{nmap_speed} -oA "{toptcpportsdir}/{address}_nmap_top_1000_tcp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

    [default.nmap-top-1000-udp]

        [default.nmap-top-1000-udp.service-detection]
        command = 'nmap {nmap_extra} -sU -sV -n -Pn --defeat-icmp-ratelimit -vv --top-ports 1000 --open -T{nmap_speed} -oA "{topudpportsdir}/{address}_nmap_top_1000_udp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

    [default.nmap-full-tcp]

        [default.nmap-full-tcp.port-scan]
        command = 'nmap {nmap_extra} -sS -vv -n -Pn -p- --open -T{nmap_speed} -oA "{fulltcpportsdir}/{address}_nmap_full_tcp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

        [default.nmap-full-tcp.service-detection]
        command = 'nmap {nmap_extra} -sS -vv -A -Pn --osscan-guess --version-all -p{ports} -T{nmap_speed} -oA "{tcpservicesdir}/{address}_nmap_full_tcp_services" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

    [default.nmap-full-udp]

        [default.nmap-full-udp.port-scan]
        command = 'nmap {nmap_extra} -sU -vv -n -Pn --defeat-icmp-ratelimit -p- --open -T{nmap_speed} -oA "{fulludpportsdir}/{address}_nmap_full_udp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

        [default.nmap-full-udp.service-detection]
        command = 'nmap {nmap_extra} -sU -vv -A -Pn --defeat-icmp-ratelimit --osscan-guess --version-all -p{ports} -T{nmap_speed} -oA "{udpservicesdir}/{address}_nmap_full_udp_services" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

[quick]

    [quick.nmap-top-100-tcp]

        [quick.nmap-top-100-tcp.service-detection]
        command = 'nmap {nmap_extra} -sS -sV --version-all -n -Pn -vv --top-ports 100 --open -T{nmap_speed} -oA "{toptcpportsdir}/{address}_nmap_top_100_tcp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

    [quick.nmap-top-100-udp]

        [quick.nmap-top-100-udp.service-detection]
        command = 'nmap {nmap_extra} -sU -A --version-all --defeat-icmp-ratelimit --defeat-icmp-ratelimit -n -Pn -vv --top-ports 100 --open -T{nmap_speed} -oA "{topudpportsdir}/{address}_nmap_top_100_udp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

    [quick.nmap-top-3000-tcp]

        [quick.nmap-top-3000-tcp.port-scan]
        command = 'nmap {nmap_extra} -sS -vv -n -Pn --top-ports 3000 --open -T{nmap_speed} -oA "{toptcpportsdir}/{address}_nmap_top_3000_tcp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

        [quick.nmap-top-3000-tcp.service-detection]
        command = 'nmap {nmap_extra} -sS -vv -A -Pn --osscan-guess --version-all -p{ports} -T{nmap_speed} -oA "{tcpservicesdir}/{address}_nmap_top_3000_tcp_services" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

    [quick.nmap-top-3000-udp]

        [quick.nmap-top-3000-udp.port-scan]
        command = 'nmap {nmap_extra} -sU -vv -n -Pn --defeat-icmp-ratelimit --top-ports 3000 --open -T{nmap_speed} -oA "{topudpportsdir}/{address}_nmap_top_3000_udp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

        [quick.nmap-top-3000-udp.service-detection]
        command = 'nmap {nmap_extra} -sU -vv -A -Pn --defeat-icmp-ratelimit --osscan-guess --version-all -p{ports} -T{nmap_speed} -oA "{udpservicesdir}/{address}_nmap_top_3000_udp_services" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

[web]

    [web.nmap-tcp]

        [web.nmap-tcp.port-scan]
        command = 'nmap {nmap_extra} -sS -vv -n -Pn -p80,443 --open -T{nmap_speed} -oA "{fulltcpportsdir}/{address}_nmap_web_tcp" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'

        [web.nmap-tcp.service-detection]
        command = 'nmap {nmap_extra} -sS -vv -A -Pn --osscan-guess --version-all -p{ports} -T{nmap_speed} -oA "{tcpservicesdir}/{address}_nmap_web_tcp_services" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/\?]+)(\s*)(?P<reason>[\w\-]+)(\s*)ttl(\s*)\d+(\s*)(?P<version>.*)$'
